all: assign2-0 assign2

assign2-0: assign2-0.c pslibrary.c
	cc -o assign2-0 assign2-0.c pslibrary.c

assign2: assign2.c pslibrary.c
	cc -o assign2 assign2.c pslibrary.c

clean:
	rm -f assign2-0 assign2 *.o

run1:
	assign2 3 8 7 3 6 3 2
run2:
	assign2 3 8 7 3 6 7 2
run3:
	assign2 4 8 7 3 6 1 2
run4:
	assign2 3 3 3 4 2 1 2
run5:
	assign2 3 3 2 3 2 1 2
run6:
	assign2 3 5 2 5 4 1 1
runex1:
	assign2 0 4 2 7 3 6 5
runex2:
	assign2 0 4 9 5 6 3 7
runtie:
	assign2 3 1 1 4 1 3 1